#!/bin/bash

rm -rf build && mkdir build && cd build

cmake .. -DOPTIMIZE="Release"
make all
valgrind --leak-check=full ./ut_reader
valgrind --leak-check=full ./ut_pitbull
valgrind --leak-check=full ./ut_analyzer